version: "3.9"

services:
  mariadb:
    networks:
      - internal
    build:
      context: ./docker
      dockerfile: mariadb_server
    environment:
      MARIADB_ROOT_PASSWORD: Password123!
    volumes:
      - mariadbdata:/data/db
    ports:
      - "3306:3306"

  app:
    build:
      context: ./docker
      dockerfile: application
    depends_on:
      - mariadb
    networks:
      - internal
    ports:
      - "3307:3306"

networks:
  internal:
    driver: bridge
volumes:
  mariadbdata:
    driver: local